/**
 * Swagger Petstore
 * Swagger Petstore (ASP.NET Core 2.0)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Pet } from './pet';

/**
 *
 */
export interface InlineResponse200 {
  /**
   * Gets or Sets Result
   */
  result?: Array<Pet>;
  /**
   * Gets or Sets Size
   */
  size?: number;
}
