/**
 * Swagger Petstore
 * Swagger Petstore (ASP.NET Core 2.0)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Tag } from './tag';
import { timestamp } from 'rxjs/operators';

/**
 *
 */
export interface Pet {
  /**
   * Gets or Sets Id
   */
  id?: number;
  /**
   * Gets or Sets Category
   */
  category?: Category;
  /**
   * Gets or Sets Name
   */
  name: string;
  /**
   * Gets or Sets PhotoUrls
   */
  photoUrls: Array<string>;
  /**
   * Gets or Sets Tags
   */
  tags?: Array<Tag>;
  /**
   * pet status in the store
   */
  status?: Pet.StatusEnum;
}
export namespace Pet {
  export type StatusEnum = 'available' | 'pending' | 'sold';
  export const StatusEnum = {
    Available: 'available' as StatusEnum,
    Pending: 'pending' as StatusEnum,
    Sold: 'sold' as StatusEnum
  };
}
