/**
 * Swagger Petstore
 * Swagger Petstore (ASP.NET Core 2.0)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 */
export interface Category {
  /**
   * Gets or Sets Id
   */
  id?: number;
  /**
   * Gets or Sets Name
   */
  name?: string;
}
